server:
  port: 9001
spring:
  application:
    name: ms-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_base?serverTimezone=UTC
    username: root
    password: lhk@123456
  jpa:
    database: mysql
    show-sql: true
  cloud:
    refresh:
      refreshable: none
  rabbitmq:
    host: 192.168.190.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
ip: 1.2.3.4.5